apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant1-admin
  namespace: tenant1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant1-role
  namespace: tenant1
rules:
- apiGroups: [""]
  resources: ["pods", "services", "pods/log", "pods/exec", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant1-role-binding
  namespace: tenant1
subjects:
- kind: ServiceAccount
  name: tenant1-admin
  namespace: tenant1
roleRef:
  kind: Role
  name: tenant1-role
  apiGroup: rbac.authorization.k8s.io
